<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PromiseCatch</title>
</head>

<body>







    <script>
        const p = new Promise((resolve, reject) => {

            reject()


        })

          //catch 的执行时机 1.当Promise的状态改为reject时 2. 当Promise中执行的代码有任何错误的时候
        p.catch(() => {//catch()和then(callback1,callback2)中的callback2 都会在代码出错的时候执行
            console.log('失败');
        })






        console.log(p);
    </script>



















</body>

</html>